services:
  postgres:
    image: postgres
    container_name: CONTAINER_NAME
    restart: always
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_DATABASE
    ports:
      - PORTS
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
